// <auto-generated />
using MP.Components.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MP.Migrations
{
    [DbContext(typeof(MPcontext))]
    partial class MPcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MP.Components.Models.Games", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameID"));

                    b.Property<string>("GameLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameID = 1,
                            GameLink = "https://play.unity.com/en/games/bd29b7bb-5721-4838-b924-f3f413c7a5bd/mp",
                            GameName = "Math Space Race",
                            Thumbnail = "[\"/Images/GameThumbnail1.png\"]"
                        },
                        new
                        {
                            GameID = 2,
                            GameLink = "https://play.unity.com/en/games/916d7430-f1a1-4bb7-924b-234c12bf7f95/count-the-animals",
                            GameName = "Counting Animals",
                            Thumbnail = "[\"/Images/GameThumbnail2.png\"]"
                        });
                });

            modelBuilder.Entity("MP.Components.Models.LeaderboardConfig", b =>
                {
                    b.Property<int>("LeaderboardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaderboardID"));

                    b.Property<string>("FirebaseUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaderboardName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeaderboardID");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            LeaderboardID = 1,
                            FirebaseUrl = "https://spacegame-745af-default-rtdb.asia-southeast1.firebasedatabase.app/",
                            LeaderboardName = "Math Space Game Leaderboard"
                        },
                        new
                        {
                            LeaderboardID = 2,
                            FirebaseUrl = "https://mpproject-ccebf-default-rtdb.asia-southeast1.firebasedatabase.app/",
                            LeaderboardName = "Counting Animals Leaderboard"
                        },
                        new
                        {
                            LeaderboardID = 3,
                            FirebaseUrl = "https://skipcounting-a54ba-default-rtdb.asia-southeast1.firebasedatabase.app/leaderboard_2s.json",
                            LeaderboardName = "Skip Counting - 2s"
                        },
                        new
                        {
                            LeaderboardID = 4,
                            FirebaseUrl = "https://skipcounting-a54ba-default-rtdb.asia-southeast1.firebasedatabase.app/leaderboard_5s.json",
                            LeaderboardName = "Skip Counting - 5s"
                        },
                        new
                        {
                            LeaderboardID = 5,
                            FirebaseUrl = "https://skipcounting-a54ba-default-rtdb.asia-southeast1.firebasedatabase.app/leaderboard_10s.json",
                            LeaderboardName = "Skip Counting - 10s"
                        },
                        new
                        {
                            LeaderboardID = 6,
                            FirebaseUrl = "https://skipcounting-a54ba-default-rtdb.asia-southeast1.firebasedatabase.app/leaderboard_random.json",
                            LeaderboardName = "Skip Counting - Everything"
                        });
                });

            modelBuilder.Entity("MP.Components.Models.Lessons", b =>
                {
                    b.Property<int>("LessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonID"));

                    b.Property<string>("LessonLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonID");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            LessonID = 1,
                            LessonLink = "https://play.unity.com/en/games/cb9c9d93-d188-45d0-9c0d-ff33257c0d08/learning-number-recognition",
                            LessonName = "Learning Number Recognition",
                            Thumbnail = "[\"/Images/LessonThumbnail1.png\"]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
